[package]
name = "my_opengl_game"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.1.0"
hashbrown = "0.15.0"
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.10"
log = "0.4"
wgpu = "22.0"