[package]
name = "my_opengl_game"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.1.0"
hashbrown = "0.15.0"
gl = "0.14"
glutin = "0.29"
nalgebra = "0.33.1"
noise = "0.9.0"
rayon = "1.10.0"
